server:
  port: 9090

# 数据库配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root   #本地的数据库用户名
    password: 123456 #本地的数据库密码
    url: jdbc:mysql://localhost:3306/xm_secondhand?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 10 # Lettuce连接池最大活跃连接数
        max-idle: 5    # Lettuce连接池最大空闲连接数
        min-idle: 1    # Lettuce连接池最小空闲连接数


# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

ip: localhost

knife4j:
  enable: true #是否开启Swagger
  basic:
    enable: true  #进入界面是否需要账号密码
    username: admin
    password: admin